steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/wae-resurces/n8n:latest', '.']
    id: 'build'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/wae-resurces/n8n:latest']
    id: 'push'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'n8n'
      - '--image'
      - 'gcr.io/wae-resurces/n8n:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--port'
      - '80'
      - '--timeout'
      - '300s'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '1'
      - '--ingress'
      - 'all'
      - '--allow-unauthenticated'
      - '--set-env-vars=^|^N8N_HOST=0.0.0.0|N8N_PORT=80|N8N_PROTOCOL=https|N8N_EDITOR_BASE_URL=https://n8n-public-230877802260.europe-west1.run.app|WEBHOOK_URL=https://n8n-public-230877802260.europe-west1.run.app|N8N_BASIC_AUTH_ACTIVE=true|N8N_BASIC_AUTH_USER=info@weareengineer.com|N8N_BASIC_AUTH_PASSWORD=Wae_n8n123|N8N_DIAGNOSTICS_ENABLED=true|EXECUTIONS_PROCESS=main|N8N_PUBLIC_API_DISABLED=false'
      - '--health-path=/healthz'
      - '--health-check-timeout=5s'
      - '--health-interval=30s'
      - '--health-retries=3'

# Images created by the build
images:
  - 'gcr.io/wae-resurces/n8n:latest'
